using System;
using System.Collections.Generic;

#nullable disable

namespace InformeUNIDA.Models
{
    public partial class EvaluacionPotencial
    {
        public int? Cevaluacion { get; set; }
        public int? Cpersona { get; set; }
        public short? Preg001 { get; set; }
        public short? Preg002 { get; set; }
        public short? Preg003 { get; set; }
        public short? Preg004 { get; set; }
        public short? Preg005 { get; set; }
        public short? Preg006 { get; set; }
        public short? Preg007 { get; set; }
        public short? Preg008 { get; set; }
        public short? Preg009 { get; set; }
        public short? Preg010 { get; set; }
        public short? Preg011 { get; set; }
        public short? Preg012 { get; set; }
        public short? Preg013 { get; set; }
        public short? Preg014 { get; set; }
        public short? Preg015 { get; set; }
        public short? Preg016 { get; set; }
        public short? Preg017 { get; set; }
        public short? Preg018 { get; set; }
        public short? Preg019 { get; set; }
        public short? Preg020 { get; set; }
        public short? Preg021 { get; set; }
        public short? Preg022 { get; set; }
        public short? Preg023 { get; set; }
        public short? Preg024 { get; set; }
        public short? Preg025 { get; set; }
        public short? Preg026 { get; set; }
        public short? Preg027 { get; set; }
        public short? Preg028 { get; set; }
        public short? Preg029 { get; set; }
        public short? Preg030 { get; set; }
        public short? Preg031 { get; set; }
        public short? Preg032 { get; set; }
        public short? Preg033 { get; set; }
        public short? Preg034 { get; set; }
        public short? Preg035 { get; set; }
        public short? Preg036 { get; set; }
        public short? Preg037 { get; set; }
        public short? Preg038 { get; set; }
        public short? Preg039 { get; set; }
        public short? Preg040 { get; set; }
        public short? Preg041 { get; set; }
        public short? Preg042 { get; set; }
        public short? Preg043 { get; set; }
        public short? Preg044 { get; set; }
        public short? Preg045 { get; set; }
        public short? Preg046 { get; set; }
        public short? Preg047 { get; set; }
        public short? Preg048 { get; set; }
        public short? Preg049 { get; set; }
        public short? Preg050 { get; set; }
        public short? Preg051 { get; set; }
        public short? Preg052 { get; set; }
        public short? Preg053 { get; set; }
        public short? Preg054 { get; set; }
        public short? Preg055 { get; set; }
        public short? Preg056 { get; set; }
        public short? Preg057 { get; set; }
        public short? Preg058 { get; set; }
        public short? Preg059 { get; set; }
        public short? Preg060 { get; set; }
        public short? Preg061 { get; set; }
        public short? Preg062 { get; set; }
        public short? Preg063 { get; set; }
        public short? Preg064 { get; set; }
        public short? Preg065 { get; set; }
        public short? Preg066 { get; set; }
        public short? Preg067 { get; set; }
        public short? Preg068 { get; set; }
        public short? Preg069 { get; set; }
        public short? Preg070 { get; set; }
        public short? Preg071 { get; set; }
        public short? Preg072 { get; set; }
        public short? Preg073 { get; set; }
        public short? Preg074 { get; set; }
        public short? Preg075 { get; set; }
        public short? Preg076 { get; set; }
        public short? Preg077 { get; set; }
        public short? Preg078 { get; set; }
        public short? Preg079 { get; set; }
        public short? Preg080 { get; set; }
        public short? Preg081 { get; set; }
        public short? Preg082 { get; set; }
        public short? Preg083 { get; set; }
        public short? Preg084 { get; set; }
        public short? Preg085 { get; set; }
        public short? Preg086 { get; set; }
        public short? Preg087 { get; set; }
        public short? Preg088 { get; set; }
        public short? Preg089 { get; set; }
        public short? Preg090 { get; set; }
        public short? Preg091 { get; set; }
        public short? Preg092 { get; set; }
        public short? Preg093 { get; set; }
        public short? Preg094 { get; set; }
        public short? Preg095 { get; set; }
        public short? Preg096 { get; set; }
        public short? Preg097 { get; set; }
        public short? Preg098 { get; set; }
        public short? Preg099 { get; set; }
        public short? Preg100 { get; set; }
        public short? Preg101 { get; set; }
        public short? Preg102 { get; set; }
        public short? Preg103 { get; set; }
        public short? Preg104 { get; set; }
        public short? Preg105 { get; set; }
        public short? Preg106 { get; set; }
        public short? Preg107 { get; set; }
        public short? Preg108 { get; set; }
        public short? Preg109 { get; set; }
        public short? Preg110 { get; set; }
        public short? Preg111 { get; set; }
        public short? Preg112 { get; set; }
        public short? Preg113 { get; set; }
        public short? Preg114 { get; set; }
        public short? Preg115 { get; set; }
        public short? Preg116 { get; set; }
        public short? Preg117 { get; set; }
        public short? Preg118 { get; set; }
        public short? Preg119 { get; set; }
        public short? Preg120 { get; set; }
        public short? Preg121 { get; set; }
        public short? Preg122 { get; set; }
        public short? Preg123 { get; set; }
        public short? Preg124 { get; set; }
        public short? Preg125 { get; set; }
        public short? Preg126 { get; set; }
        public short? Preg127 { get; set; }
        public short? Preg128 { get; set; }
        public short? Preg129 { get; set; }
        public short? Preg130 { get; set; }
        public short? Preg131 { get; set; }
        public short? Preg132 { get; set; }
        public short? Preg133 { get; set; }
        public short? Preg134 { get; set; }
        public short? Preg135 { get; set; }
        public short? Preg136 { get; set; }
        public short? Preg137 { get; set; }
        public short? Preg138 { get; set; }
        public short? Preg139 { get; set; }
        public short? Preg140 { get; set; }
    }
}
